apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce
  labels:
    app: ecommerce-app
    version: canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce-app
        version: canary
    spec:
      containers:
      - name: ecommerce-app
        image: your-dockerhub-username/dashing-ecommerce:v1.1.0-canary
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "debug"
        - name: VERSION
          value: "v1.1.0-canary"
