apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app
  namespace: ecommerce
  labels:
    app: ecommerce-app
    version: canary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecommerce-app
        version: canary
    spec:
      containers:
      - name: ecommerce-app
        image: tohidazure/k8s-ecommerce:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "debug"
        - name: VERSION
          value: "v1.1.0-canary"
