apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce

resources:
- ../../base

patchesStrategicMerge:
- ecommerce-deployment-patch.yaml
- mongodb-deployment-patch.yaml
- hpa-patch.yaml

replicas:
- name: ecommerce-app
  count: 1
- name: mongodb
  count: 1

images:
- name: dashing-ecommerce
  newName: your-dockerhub-username/dashing-ecommerce
  newTag: v1.0.0

configMapGenerator:
- name: ecommerce-config
  literals:
  - NODE_ENV=production
  - NEXTAUTH_URL=https://ecommerce.example.com
  - MONGODB_URI=mongodb://mongodb-service:27017/ecommerce_prod
