apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- mongodb-deployment.yaml
- ecommerce-deployment.yaml
- hpa.yaml

commonLabels:
  app.kubernetes.io/name: dashing-ecommerce
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: ecommerce-app
