apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- configmap.yaml
- mongodb-exporter-fixed.yaml
- ecommerce-deployment.yaml
- prometheus-enhanced.yaml
- grafana-dashboard-configmap.yaml
- hpa.yaml
- nodeport-services.yaml
- metrics-server-simple.yaml

# Note: commonLabels can cause selector conflicts with existing deployments
# Use individual file application instead: kubectl apply -f k8s/base/
