apiVersion: v1
kind: Service
metadata:
  name: ecommerce-nodeport
  namespace: ecommerce
  labels:
    app: ecommerce-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    # nodePort not specified - Kubernetes will auto-assign random port
    protocol: TCP
    name: http
  selector:
    app: ecommerce-app
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nodeport
  namespace: ecommerce
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    # nodePort not specified - Kubernetes will auto-assign random port
    protocol: TCP
    name: http
  selector:
    app: grafana
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: ecommerce
  labels:
    app: prometheus
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    # nodePort not specified - Kubernetes will auto-assign random port
    protocol: TCP
    name: http
  selector:
    app: prometheus
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  namespace: ecommerce
  labels:
    app: mongodb
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    # nodePort not specified - Kubernetes will auto-assign random port
    protocol: TCP
    name: mongodb
  - port: 9216
    targetPort: 9216
    # nodePort not specified - Kubernetes will auto-assign random port
    protocol: TCP
    name: metrics
  selector:
    app: mongodb
